"""update

Revision ID: a75f4b9e376c
Revises: 5c1bb442af53
Create Date: 2021-12-16 16:04:46.672100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a75f4b9e376c'
down_revision = '5c1bb442af53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
